version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file final.yml  --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - final.yml
    - outputSamTemplate.yml
